repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--select", "F,E9"]

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        files: ^(scripts/|tests/|train_net\.py|test_net\.py|demo_image\.py|preprocess/build_open_vocab\.py)
